// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shipping.Infrastructure.Persistence;

#nullable disable

namespace Shipping.Infrastructure.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    partial class ShippingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LabelTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PoReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PrintRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReviewDecision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceFileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SourceRowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ShipmentBatches_BatchNumber");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_ShipmentBatches_CreatedAtUtc");

                    b.HasIndex("PoReference")
                        .HasDatabaseName("IX_ShipmentBatches_PoReference");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ShipmentBatches_Status");

                    b.ToTable("ShipmentBatches", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DueDate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPrinted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LabelCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PoItem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PrintedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("RunNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ShipmentBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Store")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PartNo")
                        .HasDatabaseName("IX_ShipmentBatchItems_PartNo");

                    b.HasIndex("ShipmentBatchId")
                        .HasDatabaseName("IX_ShipmentBatchItems_BatchId");

                    b.HasIndex("ShipmentBatchId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ShipmentBatchItems_BatchId_LineNumber");

                    b.ToTable("ShipmentBatchItems", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatchRowError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipmentBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentBatchId")
                        .HasDatabaseName("IX_ShipmentBatchRowErrors_BatchId");

                    b.HasIndex("ShipmentBatchId", "RowNumber")
                        .HasDatabaseName("IX_ShipmentBatchRowErrors_BatchId_Row");

                    b.ToTable("ShipmentBatchRowErrors", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatchItem", b =>
                {
                    b.HasOne("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatch", "ShipmentBatch")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBatch");
                });

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatchRowError", b =>
                {
                    b.HasOne("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatch", "ShipmentBatch")
                        .WithMany("RowErrors")
                        .HasForeignKey("ShipmentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBatch");
                });

            modelBuilder.Entity("Shipping.Domain.Aggregates.ShipmentBatchAggregate.ShipmentBatch", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("RowErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
