// <auto-generated />
using System;
using EDI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EDI.Infrastructure.Migrations
{
    [DbContext(typeof(EdiDbContext))]
    [Migration("20260227153355_AddConfigDrivenEdi")]
    partial class AddConfigDrivenEdi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("edi")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EDI.Domain.Aggregates.EdiFileJobAggregate.EdiFileJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AppliedRecords")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ParsedRecords")
                        .HasColumnType("integer");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("PartnerCode", "Sha256")
                        .IsUnique();

                    b.ToTable("EdiFileJobs", "edi");
                });

            modelBuilder.Entity("EDI.Domain.Entities.EdiColumnDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("String");

                    b.Property<string>("DisplayLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FileTypeConfigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeConfigId", "Ordinal")
                        .IsUnique();

                    b.ToTable("EdiColumnDefinitions", "edi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000001"),
                            ColumnName = "ForecastId",
                            DataType = "String",
                            DisplayLabel = "Forecast ID",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = true,
                            MaxLength = 50,
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000002"),
                            ColumnName = "ItemCode",
                            DataType = "String",
                            DisplayLabel = "Item Code",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = true,
                            MaxLength = 50,
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000003"),
                            ColumnName = "Description",
                            DataType = "String",
                            DisplayLabel = "Description",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = false,
                            MaxLength = 255,
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000004"),
                            ColumnName = "Quantity",
                            DataType = "Decimal",
                            DisplayLabel = "Quantity",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = true,
                            Ordinal = 3
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000005"),
                            ColumnName = "UoM",
                            DataType = "String",
                            DisplayLabel = "Unit",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = false,
                            MaxLength = 20,
                            Ordinal = 4
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0001-0001-000000000006"),
                            ColumnName = "DueDate",
                            DataType = "Date",
                            DisplayLabel = "Due Date",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            IsRequired = true,
                            Ordinal = 5
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000001"),
                            ColumnName = "PoNumber",
                            DataType = "String",
                            DisplayLabel = "PO Number",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = true,
                            MaxLength = 50,
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000002"),
                            ColumnName = "PoItem",
                            DataType = "String",
                            DisplayLabel = "PO Item",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = true,
                            MaxLength = 10,
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000003"),
                            ColumnName = "ItemCode",
                            DataType = "String",
                            DisplayLabel = "Item Code",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = true,
                            MaxLength = 50,
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000004"),
                            ColumnName = "Description",
                            DataType = "String",
                            DisplayLabel = "Description",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = false,
                            MaxLength = 255,
                            Ordinal = 3
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000005"),
                            ColumnName = "Quantity",
                            DataType = "Decimal",
                            DisplayLabel = "Quantity",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = true,
                            Ordinal = 4
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000006"),
                            ColumnName = "UoM",
                            DataType = "String",
                            DisplayLabel = "Unit",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = false,
                            MaxLength = 20,
                            Ordinal = 5
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000007"),
                            ColumnName = "UnitPrice",
                            DataType = "Decimal",
                            DisplayLabel = "Unit Price",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = false,
                            Ordinal = 6
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000008"),
                            ColumnName = "DueDate",
                            DataType = "Date",
                            DisplayLabel = "Due Date",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = true,
                            Ordinal = 7
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000009"),
                            ColumnName = "Currency",
                            DataType = "String",
                            DisplayLabel = "Currency",
                            FileTypeConfigId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            IsRequired = false,
                            MaxLength = 10,
                            Ordinal = 8
                        });
                });

            modelBuilder.Entity("EDI.Domain.Entities.EdiFileTypeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue(",");

                    b.Property<int>("DetectionPriority")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FilenamePrefixPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasHeaderRow")
                        .HasColumnType("boolean");

                    b.Property<int>("HeaderLineCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxFileSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(52428800L);

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SkipLines")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("EdiFileTypeConfigs", "edi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Delimiter = ",",
                            DetectionPriority = 10,
                            DisplayName = "SAP MCP Forecast",
                            FileTypeCode = "SAP_FORECAST",
                            FilenamePrefixPattern = "^F",
                            HasHeaderRow = true,
                            HeaderLineCount = 1,
                            IsActive = true,
                            MaxFileSizeBytes = 52428800L,
                            SchemaVersion = "1.0",
                            SkipLines = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Delimiter = ",",
                            DetectionPriority = 20,
                            DisplayName = "SAP MCP Purchase Order",
                            FileTypeCode = "SAP_PO",
                            FilenamePrefixPattern = "^P",
                            HasHeaderRow = true,
                            HeaderLineCount = 1,
                            IsActive = true,
                            MaxFileSizeBytes = 52428800L,
                            SchemaVersion = "1.0",
                            SkipLines = 0
                        });
                });

            modelBuilder.Entity("EDI.Domain.Entities.EdiStagingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParsedColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationErrorsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "RowIndex")
                        .IsUnique();

                    b.HasIndex("JobId", "IsSelected", "IsValid");

                    b.ToTable("EdiStagingRows", "edi");
                });

            modelBuilder.Entity("EDI.Domain.Entities.PartnerProfile", b =>
                {
                    b.Property<string>("PartnerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ArchivePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InboxPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProcessingPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("PartnerCode");

                    b.ToTable("PartnerProfiles", "edi");

                    b.HasData(
                        new
                        {
                            PartnerCode = "SAMPLE01",
                            ArchivePath = "/data/edi/SAMPLE01/archive",
                            DisplayName = "Sample Partner 01",
                            ErrorPath = "/data/edi/SAMPLE01/error",
                            Format = "csv",
                            InboxPath = "/data/edi/SAMPLE01/inbox",
                            ProcessingPath = "/data/edi/SAMPLE01/processing",
                            SchemaVersion = "1.0"
                        });
                });

            modelBuilder.Entity("EDI.Domain.Entities.PurchaseOrderStagingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("BoiName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("DueQty")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PoItem")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PoStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawLine")
                        .HasColumnType("text");

                    b.Property<string>("Um")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("HeaderId");

                    b.ToTable("PurchaseOrderStagingDetails", "edi");
                });

            modelBuilder.Entity("EDI.Domain.Entities.PurchaseOrderStagingHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("PoFileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("TransmissionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("TransmissionTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrderStagingHeaders", "edi");
                });

            modelBuilder.Entity("EDI.Infrastructure.Persistence.ItemMasterStagingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uom")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Staging_ItemMaster", "edi");
                });

            modelBuilder.Entity("EDI.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "edi");
                });

            modelBuilder.Entity("EDI.Domain.Entities.EdiColumnDefinition", b =>
                {
                    b.HasOne("EDI.Domain.Entities.EdiFileTypeConfig", "FileTypeConfig")
                        .WithMany("Columns")
                        .HasForeignKey("FileTypeConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileTypeConfig");
                });

            modelBuilder.Entity("EDI.Domain.Entities.PurchaseOrderStagingDetail", b =>
                {
                    b.HasOne("EDI.Domain.Entities.PurchaseOrderStagingHeader", "Header")
                        .WithMany("Details")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("EDI.Domain.Entities.EdiFileTypeConfig", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("EDI.Domain.Entities.PurchaseOrderStagingHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
